# Regression Analysis

### Step 1: Importing Libraries

In [1]:
#Importing all relevant libraries

import numpy as np
import pandas as pd
import scipy.stats as stats
from sklearn.linear_model import LinearRegression
from sklearn import linear_model
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

### Step 2: Cleaning Control Variables

In [2]:
#Load listings dataset

df = pd.read_csv('C:/Users/chris/Desktop/Listings+Frequency_Reduced.csv')

#Cleaning variables

#Bedrooms
df['bedrooms'].fillna(int(df['bedrooms'].mean()), inplace = True)

#Price
df['price'] = df['price'].str.replace(',','')
df['price'] = df['price'].str.replace('$','')
df['price'] = df.price.astype(float)

#Bathrooms
df['bathrooms_text'] = df['bathrooms_text'].str.replace('[abcdefghijklmnopqrstuvwxyzPHS-]','')
df['bathrooms_text'] = df['bathrooms_text'].str.replace(' ','')
df = df[df.bathrooms_text != '']
df['bathrooms_text'] = df.bathrooms_text.astype(float)
df['bathrooms_text'].fillna(int(df['bathrooms_text'].mean()), inplace = True)

<ipython-input-2-dbe99bd92e3f>:12: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  df['price'] = df['price'].str.replace('$','')
<ipython-input-2-dbe99bd92e3f>:16: FutureWarning: The default value of regex will change from True to False in a future version.
  df['bathrooms_text'] = df['bathrooms_text'].str.replace('[abcdefghijklmnopqrstuvwxyzPHS-]','')

In [3]:
df.head()

,Unnamed: 0,id,Topic 0,Topic 1,Topic 2,Topic 3,Topic 4,Topic 5,Topic 6,Topic 7,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,0,2601191,1,5,15,15,10,17,10,19,...,5.0,4.80,4.60,NaN,f,1,1,0,0,0.06
1,1,10805394,3,6,15,18,8,19,8,18,...,4.4,4.60,4.40,NaN,f,1,0,1,0,0.14
2,2,51465104,3,9,14,13,11,17,6,18,...,5.0,4.75,4.75,NaN,f,1,1,0,0,1.18
3,3,49286229,3,4,10,17,12,15,5,15,...,5.0,5.00,4.50,NaN,f,1,1,0,0,0.64
4,4,30439280,5,10,12,16,12,17,7,17,...,5.0,4.67,4.67,NaN,t,1,1,0,0,0.08

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 24251 entries, 0 to 24302
Data columns (total 96 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Unnamed: 0                                    24251 non-null  int64
 1   id                                            24251 non-null  int64
 2   Topic 0                                       24251 non-null  int64
 3   Topic 1                                       24251 non-null  int64
 4   Topic 2                                       24251 non-null  int64
 5   Topic 3                                       24251 non-null  int64
 6   Topic 4                                       24251 non-null  int64
 7   Topic 5                                       24251 non-null  int64
 8   Topic 6                                       24251 non-null  int64
 9   Topic 7                                       24251 non-null  int64
 10  Topic 8                                       24251 non-null  int64
 11  Topic 9                                       24251 non-null  int64
 12  Topic 10                                      24251 non-null  int64
 13  Topic 11                                      24251 non-null  int64
 14  Topic 12                                      24251 non-null  int64
 15  Topic 13                                      24251 non-null  int64
 16  Topic 14                                      24251 non-null  int64
 17  Topic 15                                      24251 non-null  int64
 18  Topic 16                                      24251 non-null  int64
 19  Topic 17                                      24251 non-null  int64
 20  Topic 18                                      24251 non-null  int64
 21  Topic 19                                      24251 non-null  int64
 22  Avg                                           24251 non-null  float64
 23  listing_url                                   24251 non-null  object
 24  scrape_id                                     24251 non-null  int64
 25  last_scraped                                  24251 non-null  object
 26  name                                          24248 non-null  object
 27  description                                   24028 non-null  object
 28  neighborhood_overview                         18615 non-null  object
 29  picture_url                                   24251 non-null  object
 30  host_id                                       24251 non-null  int64
 31  host_url                                      24251 non-null  object
 32  host_name                                     24229 non-null  object
 33  host_since                                    24229 non-null  object
 34  host_location                                 24208 non-null  object
 35  host_about                                    16005 non-null  object
 36  host_response_time                            14015 non-null  object
 37  host_response_rate                            14015 non-null  object
 38  host_acceptance_rate                          15074 non-null  object
 39  host_is_superhost                             24229 non-null  object
 40  host_thumbnail_url                            24229 non-null  object
 41  host_picture_url                              24229 non-null  object
 42  host_neighbourhood                            18592 non-null  object
 43  host_listings_count                           24229 non-null  float64
 44  host_total_listings_count                     24229 non-null  float64
 45  host_verifications                            24251 non-null  object
 46  host_has_profile_pic                          24229 non-null  object
 47  host_identity_verified                        24229 non-null  object
 48  neighbourhood                                 18615 non-null  object
 49  neighbourhood_cleansed                        24251 non-null  object
 50  neighbourhood_group_cleansed                  0 non-null      float64
 51  latitude                                      24251 non-null  float64
 52  longitude                                     24251 non-null  float64
 53  property_type                                 24251 non-null  object
 54  room_type                                     24251 non-null  object
 55  accommodates                                  24251 non-null  int64
 56  bathrooms                                     0 non-null      float64
 57  bathrooms_text                                24251 non-null  float64
 58  bedrooms                                      24251 non-null  float64
 59  beds                                          23258 non-null  float64
 60  amenities                                     24251 non-null  object
 61  price                                         24251 non-null  float64
 62  minimum_nights                                24251 non-null  int64
 63  maximum_nights                                24251 non-null  int64
 64  minimum_minimum_nights                        24250 non-null  float64
 65  maximum_minimum_nights                        24250 non-null  float64
 66  minimum_maximum_nights                        24250 non-null  float64
 67  maximum_maximum_nights                        24250 non-null  float64
 68  minimum_nights_avg_ntm                        24250 non-null  float64
 69  maximum_nights_avg_ntm                        24250 non-null  float64
 70  calendar_updated                              0 non-null      float64
 71  has_availability                              24251 non-null  object
 72  availability_30                               24251 non-null  int64
 73  availability_60                               24251 non-null  int64
 74  availability_90                               24251 non-null  int64
 75  availability_365                              24251 non-null  int64
 76  calendar_last_scraped                         24251 non-null  object
 77  number_of_reviews                             24251 non-null  int64
 78  number_of_reviews_ltm                         24251 non-null  int64
 79  number_of_reviews_l30d                        24251 non-null  int64
 80  first_review                                  24251 non-null  object
 81  last_review                                   24251 non-null  object
 82  review_scores_rating                          24251 non-null  float64
 83  review_scores_accuracy                        24251 non-null  float64
 84  review_scores_cleanliness                     24251 non-null  float64
 85  review_scores_checkin                         24251 non-null  float64
 86  review_scores_communication                   24251 non-null  float64
 87  review_scores_location                        24251 non-null  float64
 88  review_scores_value                           24251 non-null  float64
 89  license                                       0 non-null      float64
 90  instant_bookable                              24251 non-null  object
 91  calculated_host_listings_count                24251 non-null  int64
 92  calculated_host_listings_count_entire_homes   24251 non-null  int64
 93  calculated_host_listings_count_private_rooms  24251 non-null  int64
 94  calculated_host_listings_count_shared_rooms   24251 non-null  int64
 95  reviews_per_month                             24251 non-null  float64
dtypes: float64(27), int64(38), object(31)
memory usage: 17.9+ MB

### Step 3: Defining X and Y variables

In [5]:

X = df[["Topic 0","Topic 1","Topic 2","Topic 3","Topic 4",
        "Topic 5","Topic 6","Topic 7","Topic 8","Topic 9",
        "Topic 10","Topic 11","Topic 12","Topic 13","Topic 14",
        "Topic 15","Topic 16","Topic 17","Topic 18","Topic 19",
        "bedrooms","price","bathrooms_text"]]
y = df["review_scores_rating"]

### Step 4: Running Linear Regression

In [6]:
#Conduct regression on independent variables (topics, bedrooms, bathrooms, price) 
#& dependent variable (review_score_rating)


regr = linear_model.LinearRegression()
regr.fit(X, y)

LinearRegression()

In [7]:
regr.coef_

array([-4.70395727e-03,  2.72700227e-04, -5.63342836e-04,  1.29928867e-03,
        1.84548853e-04, -1.02855275e-03, -2.78083957e-03,  1.79473238e-03,
        1.13019636e-03,  2.91891920e-04, -4.30866485e-04, -1.36883831e-03,
        1.07631256e-03, -1.16969750e-03,  1.54822320e-03, -8.18279503e-04,
       -2.77366383e-04,  7.56767540e-05, -1.48344805e-03,  1.06137673e-04,
       -5.65533929e-03, -7.61808805e-07,  6.95693231e-03])

In [8]:
#Installing Stats Model library for better respresentation of Regression Results

import statsmodels.api as sm
from scipy import stats

In [9]:
est = sm.OLS(y, X)

In [10]:
est.fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                  OLS Regression Results
=========================================================================================
Dep. Variable:     review_scores_rating   R-squared (uncentered):                   0.870
Model:                              OLS   Adj. R-squared (uncentered):              0.870
Method:                   Least Squares   F-statistic:                              7045.
Date:                  Wed, 16 Mar 2022   Prob (F-statistic):                        0.00
Time:                          18:39:08   Log-Likelihood:                         -47425.
No. Observations:                 24251   AIC:                                  9.490e+04
Df Residuals:                     24228   BIC:                                  9.508e+04
Df Model:                            23
Covariance Type:              nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Topic 0           -0.0102      0.001     -9.035      0.000      -0.012      -0.008
Topic 1           -0.0017      0.001     -1.436      0.151      -0.004       0.001
Topic 2            0.0011      0.001      1.137      0.255      -0.001       0.003
Topic 3           -0.0050      0.001     -4.214      0.000      -0.007      -0.003
Topic 4           -0.0137      0.001    -10.911      0.000      -0.016      -0.011
Topic 5            0.0068      0.001      6.409      0.000       0.005       0.009
Topic 6            0.0057      0.001      5.053      0.000       0.003       0.008
Topic 7            0.0078      0.001      6.094      0.000       0.005       0.010
Topic 8           -0.0011      0.001     -0.814      0.415      -0.004       0.001
Topic 9            0.0039      0.001      3.201      0.001       0.001       0.006
Topic 10           0.0040      0.001      3.117      0.002       0.001       0.006
Topic 11          -0.0044      0.001     -3.044      0.002      -0.007      -0.002
Topic 12          -0.0173      0.001    -13.500      0.000      -0.020      -0.015
Topic 13           0.0056      0.001      4.576      0.000       0.003       0.008
Topic 14           0.0080      0.001      5.687      0.000       0.005       0.011
Topic 15           0.0084      0.002      4.794      0.000       0.005       0.012
Topic 16           0.0031      0.001      2.582      0.010       0.001       0.005
Topic 17           0.0077      0.002      4.658      0.000       0.004       0.011
Topic 18          -0.0101      0.002     -5.107      0.000      -0.014      -0.006
Topic 19          -0.0025      0.002     -1.071      0.284      -0.007       0.002
bedrooms           0.6305      0.017     36.964      0.000       0.597       0.664
price          -1.974e-05    4.2e-05     -0.470      0.638      -0.000    6.26e-05
bathrooms_text     2.0753      0.020    101.991      0.000       2.035       2.115
==============================================================================
Omnibus:                    18266.978   Durbin-Watson:                   1.569
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1158326.515
Skew:                          -3.065   Prob(JB):                         0.00
Kurtosis:                      36.298   Cond. No.                     1.06e+03
==============================================================================

Notes:
[1] RÂ² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 1.06e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""